pre-commit:
  jobs:
    - name: Python Format
      glob: "*.py"
      run: uv format --check

    - name: Python Lint
      glob: "*.py"
      run: uv run ruff check

    - name: Python Type
      glob: "*.py"
      run: uv run mypy .
