# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\nhelloworld\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x04\n\x10ScalarValueTypes\x12\x0e\n\x06\x64ouble\x18\x01 \x01(\x01\x12\r\n\x05\x66loat\x18\x02 \x01(\x02\x12\r\n\x05int32\x18\x03 \x01(\x05\x12\r\n\x05int64\x18\x04 \x01(\x03\x12\x0e\n\x06uint32\x18\x05 \x01(\r\x12\x0e\n\x06uint64\x18\x06 \x01(\x04\x12\x0e\n\x06sint32\x18\x07 \x01(\x11\x12\x0e\n\x06sint64\x18\x08 \x01(\x12\x12\x0f\n\x07\x66ixed32\x18\t \x01(\x07\x12\x0f\n\x07\x66ixed64\x18\n \x01(\x06\x12\x10\n\x08sfixed32\x18\x0b \x01(\x0f\x12\x10\n\x08sfixed64\x18\x0c \x01(\x10\x12\x0c\n\x04\x62ool\x18\r \x01(\x08\x12\x0e\n\x06string\x18\x0e \x01(\t\x12\r\n\x05\x62ytes\x18\x0f \x01(\x0c\x12\r\n\x05\x61rray\x18\x10 \x03(\t\x12\x32\n\x03map\x18\x11 \x03(\x0b\x32%.helloworld.ScalarValueTypes.MapEntry\x12/\n\tenumvalue\x18\x12 \x01(\x0e\x32\x1c.helloworld.EnumerationValue\x12\x12\n\x08oneint32\x18\x13 \x01(\x05H\x00\x12\x13\n\tonestring\x18\x14 \x01(\tH\x00\x12!\n\x03\x61ny\x18\x15 \x01(\x0b\x32\x14.google.protobuf.Any\x12-\n\ttimestamp\x18\x16 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x42\x0b\n\toneofname\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t*6\n\x10\x45numerationValue\x12\n\n\x06VALUE0\x10\x00\x12\n\n\x06VALUE1\x10\x01\x12\n\n\x06VALUE2\x10\x02\x32\xf4\x01\n\x03\x41pi\x12\x42\n\x04\x43\x61ll\x12\x1c.helloworld.ScalarValueTypes\x1a\x1c.helloworld.ScalarValueTypes\x12\x39\n\x08\x44ownload\x12\x16.google.protobuf.Empty\x1a\x13.helloworld.Message0\x01\x12\x37\n\x06Upload\x12\x13.helloworld.Message\x1a\x16.google.protobuf.Empty(\x01\x12\x35\n\x05\x41sync\x12\x13.helloworld.Message\x1a\x13.helloworld.Message(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCALARVALUETYPES_MAPENTRY']._loaded_options = None
  _globals['_SCALARVALUETYPES_MAPENTRY']._serialized_options = b'8\001'
  _globals['_ENUMERATIONVALUE']._serialized_start=703
  _globals['_ENUMERATIONVALUE']._serialized_end=757
  _globals['_SCALARVALUETYPES']._serialized_start=119
  _globals['_SCALARVALUETYPES']._serialized_end=673
  _globals['_SCALARVALUETYPES_MAPENTRY']._serialized_start=618
  _globals['_SCALARVALUETYPES_MAPENTRY']._serialized_end=660
  _globals['_MESSAGE']._serialized_start=675
  _globals['_MESSAGE']._serialized_end=701
  _globals['_API']._serialized_start=760
  _globals['_API']._serialized_end=1004
# @@protoc_insertion_point(module_scope)
